#!/bin/bash

# pclfofar, PCL Find Original Filename and Rename
# oh, ho ho, what have you gotten yourself in to? if you're looking at this file
# it's because _someone_ is storing windows print jobs _in_ their print queue
# and you just deleted them. you undeleted them using super l33t undelete tools
# and now you want to rename your .SPL files back to what they originally were.
# WHO WOULD EVER NEED THIS?!?! no one. my company did. once. so here it is...

# put this in the same folder as all your .SPL files

# run through all the files in the directory
for fileName in /*
do

# this function finds the original filename in the .SPL file. it's on line 8
function grabFileName {
# this line finds it on line 8, and removes the quotes and all that
sed -n '8p' $fileName | grep -o '\".*\"' | tr -d '"';
}

# this line sets the bash variable of the new filename
newFileName=$(grabFileName)

# this line does the renaming, and makes sure it doesn't clobber it, incase the print queue had multiples
# of the same job name
mv --backup=numbered $fileName "$newFileName"

done

echo "                              GtiittitttjjjfjjffffffffjjjjjjjjfLEW                                 "
echo "                           WGtittttttjjjffffffLfffLLffjjjttiittiiijLE                              "
echo "                          DtittjtttjjffffLLLLLfLLLLLLfffjttitttiiiiitL                             "
echo "                         KiitttjjjtjjfLLLGGGLfLGGGLLLLLfjtttttttttiiij                             "
echo "                         jtttttjjjjtjfLGGGGGLLGLLLLLLLfjttiiiiiiiiiiitW                            "
echo "                        EttttjjjjjtttfLGGGGLLLLLLLLLLfjjtii;iiiiiiiiiiE                            "
echo "                        jjjjjjffffjjjjfGGGGLLLLLGGLLfjjti;;iittttttiiiL                            "
echo "                       DtjjjjjjjfffffffLLLLLLLLGLLLLfffjjttttttttjjtiij                            "
echo "                       Ltfffjjjjjjfjjjjfffffffffjjjtttiiiiiiitttjjjjttt                            "
echo "                       Ltffffjjjtttttttjjjjjjtttiiii;;;;,,;;;iitttjjjjtK                           "
echo "                       jtffjjtttiiitttttjjjjtttiiiiii;;,,...,,;;iiijjjjD                           "
echo "                       ttfjjjtttiiiitttjjjjtttttiiiii;;,......,;iiiitjjL                           "
echo "                       ttfffjtttiiiittjjjjjjtttttiiii;,,.......,iti;ittjW                          "
echo "                       ttfffttttiiiittjjjjjjjttttiii;;,,,...,,,,;ttiiittW                          "
echo "                       tjfLjjttiiiitttjjjjjjjjttttii;;,,,...,,,,;tjtiitf                           "
echo "                      WtjLLjjttiiiitttjjjjjjjjttttii;;,,,,.,.,,,itjtittL                           "
echo "                      KtfLLjjttiiiitttjjjjjjjjjtttii;;,,,....,,;itjjjjjD                           "
echo "                      KtLLLjtttiiiittjjjjjjjjjjjttii;;,,,,..,,,;itjjjjjK                           "
echo "                      KtLGLjtttiitttjjjjffjjjjjjtttii;;,,,,,,,;;itjjfff                            "
echo "                      EtGGLjttttffLLGLLLLLffffjjjjfffjjti;;,,,;;;ijfffG                            "
echo "                      DjGGLjjjjjffLLGGGGLLLfffffffLLGGLLfjti;,;;;ijffLG                            "
echo "                      GtGGLjtttjjffLLGGGLfffjtttffLLLLLfjtti;;;;;ijffLLW                           "
echo "                      GtLLfjtttjfLGDDDDDGfttti;;tLLGGGGLfjti;;;;;;tjfLLD                           "
echo "                      LjjfjtttjLLLGEEEDDDLttt;,;tLGDDEEDGLfti;;;;;;ijGLfW                          "
echo "                      LLjjtttttttjfGDDDGLjttt;,;ijLGGGDGjjjji;;;;;;;tfiifW                         "
echo "                      LGjtttiiiiitffLLLLjttti;,,,ijffffji;,;;,,,;;;;;;iLfL                         "
echo "                     KLLjtttiiiiitjjffjttttti;;,,,ijjjtti;,,,,,,;;;;;;;fLL                         "
echo "                     ELftjjttiiittjjjjttiitti;;,,,,itttti;,,,,,;;;;ii;;jLL                         "
echo "                     EfjjLjttiiitjjjjttiiittti;;,,,;ittti;;,,,;;;;;tti;tLL                         "
echo "                     EtjLLtttiiittjjjjtttttfjti;;;;iiittii;;;;;;;;;jfjttfG                         "
echo "                     KttfLttttiitttjjjjjjGGffjGLiiiiitiiii;;;;;;;;,ijfjijW                         "
echo "                      ftjfjttiittttttjjjffjfftfftittttiiii;;;;;;;;;;tjtiD                          "
echo "                      Ktttttttiiittttjtttitjji;;;;iitiiiiii;;;;;;;ijjiij                           "
echo "                       ftttttiiiiitttttttttjfti;;;;iiiiii;;;;;i;;tti;iiK                           "
echo "                       Kttjjttiiiiiitttttttjjjtii;;;;;;;;;;;;;iitiii;iD                            "
echo "                        WEDLtttiiiitttttjfffffjtiii;;;;;;;;;;;ijfjtttD                             "
echo "                            jtiiiitttjfLLLLGGGLLLfjtii;;;;;iiitfDKKKW    GLK                       "
echo "                            Ltttttttjfjjjjffffjtttjjtiiiiiiiiiif        EjjfK                      "
echo "                            GtttttttjjjjjffLLLfjttitttiiiiiiiiiD        GtjfD                      "
echo "                            EtttttttjjjffLLGGGGLfjtttttiiiiii;iK        ftfLG                      "
echo "                            EttttttjjjjfLLLLLffLLfjtttttiiiii;t        WjjfLL                      "
echo "                             ttttttjjjjjjjjffjttttttttttiiii;;L       KfjjfLLW                     "
echo "                             jttttjjjttjjjffffjttttttttitii;;;D      EjjffLLG                      "
echo "                             fttttjjjjtjjffLLffjttiittttti;;;iW     GjfffLLGW                      "
echo "                             LttttjjjjjjjfLLLLffjttttttiii;;;j    WLjjfLLLGW                       "
echo "                       WDGE  DjtttjffffjffLLLLLLffjjttiiiii;iL   WfjjfLLLD                         "
echo "                     Gt;;iijLjjjttjfLLLLffffLLLLffjtiiiiiii;iE   LjjffLLf                          "
echo "                    D;;;iiiittjfffjffLGGGLLLLLLLfjjtiiiiiiiijW  GtjjffffjffLLLLLE                  "
echo "                   Ki;;i;;;;iiitjfLLLLGGDDDGGGGGLfjtii;iiiiif  DtjjjjjfffffjjjfffGW                "
echo "                   ji;;;;;;iiiitttjjfffLLGGDDGGGLfjtiiittiiitEGjtjjjjffffjjjjfffLLLK               "
echo "                   jiiiii;;iiiittttjjttiiitjfLGGLfjtiiittiijiitjjjjjjjfffjffffLLLLLG               "
echo "                   j;;iitiiiiiitttttjjjjjttiiitjffjttitjtitLjjjjjjjjjffffffffffLLLGLK              "
echo "          WDGLffjjj;,;iiittiiiiiittttttjjjjjttiiiittttjjtijfffjjjjjjfLfLfffffffffLLGGDW            "
echo "       ELt,,,,,,,,,,,,;;;;;;;;;;;;;;;iittttttttttii;itfjttjjjjjjjjjLGGGLffffffffLLLLGGK            "
echo "    WG;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiittttttiiitjjjjjjjjjjjffGGGffffffffLLLLLLGG             "
echo "   Et;;;;;;iitttiiiittiiiii;;ii;;;;;;;;;;iiiiitttttjjjjjjjjjjjjffffLGffffffffLLLLLGGGG             "
echo " Wf;;;;;;iiiiitjjtttitttittiiitttiiiii;;;iiitttjjjjjjjffffffffffLjLGLLLLLLfffLLLLLGGGD             "
echo "Di;;iittttttttjjjfjjtttjtttttitttttiijffjitjjjjjjjjfffffffffffffLjffffGLLLLLLLLLLLGGGW             "
echo "iiittttttttttjjjjjffjjjjjjtjttttttiitittjjjjjjjjjffffffffLfffffLLDGGDDfGLLLLLGLLGGGGW              "
echo "iittiiiitttttjjfffffffjjjjjjjttttttttjjjjjjfffffffffLLLLLLLLLLLLGLLLLGLGLGLDLLLLjDLDK              "
echo "iiiiiittttjjjjjfffLfffffjjjjjjjttjjjjjjfffffffffffLLLLLLffLLLLGGGLLLLGGLGGGDLLGfGGGfE              "
echo "iiiiiitjjjjjffffffLLLLLffjjjjjjjjjjfffffffffffffffLLLfffffLLLGGGGGGLGGGGGGGELDLfDGGDW              "
echo "iiiiiiitjjjjjfffffLLLffffjjjjjjjffffffffffffffffffffffffLLLLLGDDDGGDGGGGDGDEGGEGLGDE               "
echo "iiiiiiittjjffffffffffjjjfffffffffffffffffffffffffffLLLLLGGGGGGDDGDDDGDDDDDDDDDDEDGLD               "
echo "iiiiitttttjjjjjjjjjjjfffffffffffffffffffffffffLLLLLLLLGGGLGGfjjfjjffLLfffjjjiittttij               "
echo "iittjjjtttjjjjjjffffffffffffffLLLffffffffLLLLLLLLLLLLLLftifDLii;;;;;;;,,,,,,,,,,,;;;D              "
echo "ittttjjjjjjjjjfffffffffffffffffLLLfffffLLLLLLLLLLLLLftiiiitLGj;;;;;;;;;,,,,,,,,,,;i;iW             "
echo "jtjjjjjjjjjjffffffffffffffffffffLLfLfLLLLLLLLLLLLftiiiiiiiijGGt;;;;;;;;;;,,,,,,,,,;i;f             "
echo "jjjjjjjjjjffffffffffffffffLfffffLLLLLLLLLLLLLGLjiiiiiiiiiiiifGfi;;;;;;;;;;;;BRENT RAMBO            "
echo ""
